apiVersion: apps/v1
kind: Deployment
metadata:
  name: schwag-exchange
  namespace: default
  labels:
    app: schwag-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schwag-exchange
  template:
    metadata:
      labels:
        app: schwag-exchange
    spec:
      containers:
      - name: hello
        image: gcr.io/bet-andr/schwag-exhange-web:v0.4.2
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /
            port: 8888
        livenessProbe:
          httpGet:
            path: /
            port: 8888
