apiVersion: v1
kind: Service
metadata:
  name: schwag-exchange
  namespace: default
spec:
  selector:
    app: schwag-exchange
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8888
  type: NodePort
