apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: datalab@bbc.co.uk
    privateKeySecretRef:
      name: letsencrypt
    http01: {}
