apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: default
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: betandr/gollo-world:latest
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /
            port: 8888
        livenessProbe:
          httpGet:
            path: /
            port: 8888
        envFrom:
        - configMapRef:
            name: hello-config
        # - secretRef:
        #     name: andr-auth
