apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  selector:
    app: hello
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort
