apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyandr
  namespace: default
  labels:
    app: nyandr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nyandr
  template:
    metadata:
      labels:
        app: nyandr
    spec:
      containers:
      - name: hello
        image: betandr/nyandr:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
