apiVersion: v1
kind: Service
metadata:
  name: nyandr
  namespace: default
spec:
  selector:
    app: nyandr
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
